ALL:
	gcc binary_search.c -o binary_search
	g++ max_and_min.c -o max_and_min
	gcc array_shift.c -o array_shift
	gcc count_1_in_binary.c -o count_1_in_binary
	gcc my_atoi.c -o my_atoi
	gcc reverse_int.c -o reverse_int
	gcc prim.c -o prim
	gcc my_strstr.c -o my_strstr
