ALL:
	gcc mutex_condition.c -l pthread -o mutex_condition
	gcc cyclic.c -l pthread -o cyclic
	gcc sequence.c -l pthread -o sequence
	gcc semaphore.c -l pthread -o semaphore
	gcc use_semaphore.c -l pthread -o use_semaphore
	gcc multi_produ_consu.c -l pthread -o multi_produ_consu
